apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/mayurcrewale/k8s-deploy/base?ref=v1.0.0

patches:
  - path: patch/deploy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment

images:
  - name: mayur21486/helloapp
    newName: mayur21486/helloapp
    newTag: ee2c972a4054ef6968edb59ecbd4eb6f3c077dc6

nameSuffix: -dev
namespace: dev