# - op: replace
#   path: /spec/template/spec/containers/0/image
#   value: nginx:1.21.0

- op: replace
  path: /metadata/labels/app
  value: testname

- op: replace
  path: /metadata/name
  value: testname-deploy

- op: replace
  path: /spec/selector/matchLabels/app
  value: testname

- op: replace
  path: /spec/template/metadata/labels/app
  value: testname-deploy

- op: replace
  path: /spec/template/metadata/labels/app
  value: testname-deploy

- op: replace
  path: /spec/template/metadata/labels/app
  value: testname-deploy